site_name: Mòdul 0373 - Llenguatges de marques
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/0373-llenguatges-de-marques/

nav:
  - Inici: index.md
  - Presentacions: presentacions.md

theme:
  name: material
  language: ca
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

extra_css:
  - assets/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
