site_name: Apunts d'en Joan Pardo per DigiTechFP
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/apunts-jpardo20/

nav:
  - Inici: index.md
  - Mòduls de SMX:
    - 0221 Muntatge i manteniment d’equips moduls:
      - Presentacions:
        - Presentacions:  moduls/0221-muntatge-i-manteniment-d-equips/presentacions/index.html
      - Activitats:
        - Activitat mim-ud01-ae01: moduls/0221-muntatge-i-manteniment-d-equips/presentacions/mim-ud01-ae01.reveal
    - 0223 Aplicacions ofimàtiques:
      - Presentacions:
        - Presentacions:  moduls/0223-aplicacions-ofimatiques/presentacions/index.html
    - 0225 Xarxes locals:
      - Presentacions:
        - Presentacions:  moduls/0225-xarxes-locals/presentacions/index.html
    - MOPT1 Programació Python:
      - Presentacions:
        - Presentacions:  moduls/mopt1-robotica-python/presentacions/index.html
  - Mòduls de DAM:
    - 0373 - Llenguatges de marques:
      - Presentacions:
        - Presentacions:  moduls/0373-llenguatges-de-marques/presentacions/index.html
    - 0484 - Bases de dades:
      - Presentacions:
        - Presentacions:  moduls/0484-bases-de-dades/presentacions/index.html
    - 0483 - Sistemes Informàtics:
      - Presentacions:
        - Presentacions:  moduls/0483-sistemes-informatics/presentacions/index.html 

  # - <h3>Mòduls de DAM</h3>:
  
  #   - 0373 - Llenguatges de marques:
  #       - Resultats d'Aprenentatge (RA): 
  #         - apunts: moduls/0373-llenguatges-de-marques/apunts/index.html
  #       - Presentacions:
  #         - Presentacions:  moduls/0373-llenguatges-de-marques/presentacions/index.html

  


theme:
  name: material
  logo: assets/img/VERT-01-SIN-CAJA-BLANCO-RGB@2x-768x593.png
  favicon: assets/img/cropped-cropped-VERT-01-BLANCO-RGB-copia-150x150.png
  features:
    - navigation.indexes
    - navigation.sections
    
  revealjs:
    history: true
    slideNumber: true

extra_css:
  - assets/css/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
